language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - yarn build
deploy:
  provider: surge
  skip_cleanup: true
  domain: mythLabs.surge.sh
  project: ./build/
  on: React-seed-with-Travis